services:
  homenas:
    build: .
    container_name: homenas_web
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - /mnt/nas:/storage
      - /mnt/nas-hdd:/storage-hdd
      - /tmp/homenas_ssd_cache:/ssd_cache
    environment:
      - STORAGE_DIR=/storage
      - STORAGE_HDD_DIR=/storage-hdd
      - SSD_CACHE_DIR=/ssd_cache
      - MAX_CACHE_SIZE_GB=50
      - ADMIN_USER=admin
      - ADMIN_PASS=naspassword123
      - TOTP_SECRET=JBSWY3DPEHPK3PXP
      - RESEND_API_KEY=re_JQ6uJLyg_5oUMtDYUn31v7sTPU2gHSNxi
      - RESEND_FROM_EMAIL=Acme <onboarding@resend.dev>
      - NOTIFY_EMAIL=delivered@resend.dev

  samba:
    image: dperson/samba:latest
    container_name: homenas_samba
    restart: always
    ports:
      - "139:139"
      - "445:445"
    volumes:
      - /mnt/nas:/mount/storage-ssd
      - /mnt/nas-hdd:/mount/storage-hdd
    command: -s "HomeNAS-SSD;/mount/storage-ssd;yes;no;no;all;none;admin" -s "HomeNAS-HDD;/mount/storage-hdd;yes;no;no;all;none;admin" -u "admin;naspassword123"

  filebrowser:
    image: filebrowser/filebrowser:latest
    container_name: homenas_filebrowser
    restart: always
    ports:
      - "8081:80"
    volumes:
      - /mnt/nas:/srv/ssd
      - /mnt/nas-hdd:/srv/hdd
      - ./filebrowser.db:/database/filebrowser.db
      - ./filebrowser.json:/.filebrowser.json
